### ISSUE TITLE
Deprecate stateful protocol

### ISSUE THREAD

**Issue by luckysori** [comit-network/baru#54]
Before coming up with a new design, we must understand how the current actor-state based approach is problematic.
 
We could then, for example, model the protocol as a series of transactions which either party can build, sign, broadcast.

**Comment by DeliciousHair** [comment]
Proposed design using PSETs:

![new_loan_protocol](https://user-images.githubusercontent.com/6540809/129130962-b2006a5e-b9a0-47ac-ba93-d89ac21146db.png)
